// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktodo

import (
	"context"

	"github.com/minty1202/go-ddd-onion-template/internal/domain/todo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockRepository
func (_mock *MockRepository) Add(ctx context.Context, todo1 *todo.Todo) error {
	ret := _mock.Called(ctx, todo1)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *todo.Todo) error); ok {
		r0 = returnFunc(ctx, todo1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - todo1 *todo.Todo
func (_e *MockRepository_Expecter) Add(ctx interface{}, todo1 interface{}) *MockRepository_Add_Call {
	return &MockRepository_Add_Call{Call: _e.mock.On("Add", ctx, todo1)}
}

func (_c *MockRepository_Add_Call) Run(run func(ctx context.Context, todo1 *todo.Todo)) *MockRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *todo.Todo
		if args[1] != nil {
			arg1 = args[1].(*todo.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Add_Call) Return(err error) *MockRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Add_Call) RunAndReturn(run func(ctx context.Context, todo1 *todo.Todo) error) *MockRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id todo.ID) (*todo.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, todo.ID) (*todo.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, todo.ID) *todo.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*todo.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, todo.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id todo.ID
func (_e *MockRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id todo.ID)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 todo.ID
		if args[1] != nil {
			arg1 = args[1].(todo.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(todo1 *todo.Todo, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id todo.ID) (*todo.Todo, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveByID provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveByID(ctx context.Context, id todo.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, todo.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RemoveByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveByID'
type MockRepository_RemoveByID_Call struct {
	*mock.Call
}

// RemoveByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id todo.ID
func (_e *MockRepository_Expecter) RemoveByID(ctx interface{}, id interface{}) *MockRepository_RemoveByID_Call {
	return &MockRepository_RemoveByID_Call{Call: _e.mock.On("RemoveByID", ctx, id)}
}

func (_c *MockRepository_RemoveByID_Call) Run(run func(ctx context.Context, id todo.ID)) *MockRepository_RemoveByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 todo.ID
		if args[1] != nil {
			arg1 = args[1].(todo.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveByID_Call) Return(err error) *MockRepository_RemoveByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RemoveByID_Call) RunAndReturn(run func(ctx context.Context, id todo.ID) error) *MockRepository_RemoveByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, todo1 *todo.Todo) error {
	ret := _mock.Called(ctx, todo1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *todo.Todo) error); ok {
		r0 = returnFunc(ctx, todo1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - todo1 *todo.Todo
func (_e *MockRepository_Expecter) Save(ctx interface{}, todo1 interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, todo1)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, todo1 *todo.Todo)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *todo.Todo
		if args[1] != nil {
			arg1 = args[1].(*todo.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, todo1 *todo.Todo) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
