// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package db

import (
	"context"
)

const deleteTodoByID = `-- name: DeleteTodoByID :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodoByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTodoByID, id)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, body, completed, version, created_at, updated_at FROM todos
WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Completed,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTodo = `-- name: InsertTodo :exec
INSERT INTO todos (
    id, title, body, completed, version
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertTodoParams struct {
	ID        string
	Title     string
	Body      string
	Completed bool
	Version   int32
}

func (q *Queries) InsertTodo(ctx context.Context, arg InsertTodoParams) error {
	_, err := q.db.Exec(ctx, insertTodo,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Completed,
		arg.Version,
	)
	return err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET
    title = $1,
    body = $2,
    completed = $3,
    version = version + 1
WHERE id = $4 AND version = $5
RETURNING version
`

type UpdateTodoParams struct {
	Title     string
	Body      string
	Completed bool
	ID        string
	Version   int32
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Title,
		arg.Body,
		arg.Completed,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
